export var stadiumText: string = `{
    "name": "G.Buffon Hot Big&[GB]",
    "width": 630,
    "height": 350,
    "spawnDistance": 350,
    "bg": {
        "type": "grass",
        "width": 550,
        "height": 320,
        "kickOffRadius": 80,
        "cornerRadius": 0
    },
    "vertexes": [{
        "x": -550,
        "y": 320,
        "trait": "ballArea"
    }, {
        "x": -550,
        "y": 100,
        "trait": "ballArea"
    }, {
        "x": -550,
        "y": -100,
        "trait": "ballArea"
    }, {
        "x": -550,
        "y": -320,
        "trait": "ballArea"
    }, {
        "x": 550,
        "y": 320,
        "trait": "ballArea"
    }, {
        "x": 550,
        "y": 100,
        "trait": "ballArea"
    }, {
        "x": 550,
        "y": -100,
        "trait": "ballArea"
    }, {
        "x": 550,
        "y": -320,
        "trait": "ballArea"
    }, {
        "x": 0,
        "y": 320,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": 80,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -80,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -320,
        "trait": "kickOffBarrier"
    }, {
        "x": -550,
        "y": -100,
        "trait": "goalNet",
        "curve": -10,
        "color": "C7E6BD"
    }, {
        "x": -595,
        "y": -80,
        "trait": "goalNet",
        "curve": -20,
        "color": "C7E6BD"
    }, {
        "x": -595,
        "y": 80,
        "trait": "goalNet",
        "curve": -20,
        "color": "C7E6BD"
    }, {
        "x": -550,
        "y": 100,
        "trait": "goalNet",
        "curve": -10,
        "color": "C7E6BD"
    }, {
        "x": 550,
        "y": -100,
        "trait": "goalNet",
        "curve": 10,
        "color": "C7E6BD"
    }, {
        "x": 595,
        "y": -80,
        "trait": "goalNet",
        "curve": 20,
        "color": "C7E6BD"
    }, {
        "x": 595,
        "y": 80,
        "trait": "goalNet",
        "curve": 20,
        "color": "C7E6BD"
    }, {
        "x": 550,
        "y": 100,
        "trait": "goalNet",
        "curve": 10,
        "color": "C7E6BD"
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": -320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": -320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": -80
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": -320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": 80
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": -80,
        "curve": 180
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": 80,
        "curve": 180
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": -80,
        "curve": -180
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 0,
        "y": 80,
        "curve": -180
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": 100
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": -320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": 550,
        "y": -100
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": -320,
        "curve": 0
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": -100,
        "curve": 0
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 100,
        "curve": 0
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320,
        "curve": 0
    }, {
        "x": -550,
        "y": 320,
        "trait": "ballArea"
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320,
        "curve": 0
    }, {
        "x": -550,
        "y": 320,
        "trait": "ballArea"
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320
    }, {
        "bCoef": 0.1,
        "cMask": ["wall"],
        "x": -550,
        "y": 320,
        "curve": 0
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -550,
        "y": 100,
        "vis": true,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -550,
        "y": 320,
        "vis": true,
        "color": "C7E6BD"
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -557,
        "y": 101
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -557,
        "y": 318
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -563,
        "y": 100
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -563,
        "y": 318
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -569,
        "y": 99
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -569,
        "y": 317
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -575,
        "y": 97
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -576,
        "y": 317
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -583,
        "y": 97
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -584,
        "y": 318
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -554,
        "y": -318
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -554,
        "y": -101
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -560,
        "y": -319
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -560,
        "y": -101
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -566,
        "y": -320
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -566,
        "y": -102
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -572,
        "y": -322
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -573,
        "y": -102
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -580,
        "y": -322
    }, {
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -581,
        "y": -101
    }, {
        "x": 555,
        "y": -322
    }, {
        "x": 556,
        "y": -103
    }, {
        "x": 561,
        "y": -321
    }, {
        "x": 562,
        "y": -103
    }, {
        "x": 567,
        "y": -321
    }, {
        "x": 569,
        "y": -102
    }, {
        "x": 573,
        "y": -322
    }, {
        "x": 575,
        "y": -101
    }, {
        "x": 581,
        "y": -323
    }, {
        "x": 582,
        "y": -100
    }, {
        "x": 555,
        "y": 319
    }, {
        "x": 555,
        "y": 108
    }, {
        "x": 561,
        "y": 107
    }, {
        "x": 562,
        "y": 321
    }, {
        "x": 567,
        "y": 102
    }, {
        "x": 569,
        "y": 320
    }, {
        "x": 574,
        "y": 319
    }, {
        "x": 573,
        "y": 100
    }, {
        "x": 579,
        "y": 98
    }, {
        "x": 581,
        "y": 318
    }],
    "segments": [{
        "v0": 2,
        "v1": 3,
        "trait": "ballArea"
    }, {
        "v0": 4,
        "v1": 5,
        "trait": "ballArea"
    }, {
        "v0": 6,
        "v1": 7,
        "trait": "ballArea"
    }, {
        "v0": 12,
        "v1": 13,
        "trait": "goalNet",
        "curve": -10,
        "color": "C7E6BD"
    }, {
        "v0": 13,
        "v1": 14,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": -20
    }, {
        "v0": 14,
        "v1": 15,
        "trait": "goalNet",
        "curve": -10,
        "color": "C7E6BD"
    }, {
        "v0": 16,
        "v1": 17,
        "trait": "goalNet",
        "curve": 10,
        "color": "C7E6BD"
    }, {
        "v0": 17,
        "v1": 18,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": 20
    }, {
        "v0": 18,
        "v1": 19,
        "trait": "goalNet",
        "curve": 10,
        "color": "C7E6BD"
    }, {
        "v0": 8,
        "v1": 9,
        "trait": "kickOffBarrier"
    }, {
        "v0": 9,
        "v1": 10,
        "trait": "kickOffBarrier",
        "curve": 180,
        "cGroup": ["blueKO"]
    }, {
        "v0": 9,
        "v1": 10,
        "trait": "kickOffBarrier",
        "curve": -180,
        "cGroup": ["redKO"]
    }, {
        "v0": 10,
        "v1": 11,
        "trait": "kickOffBarrier"
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 20,
        "v1": 21
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 22,
        "v1": 23
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 24,
        "v1": 25
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 26,
        "v1": 27
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 28,
        "v1": 29,
        "curve": 180
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 30,
        "v1": 31,
        "curve": -180
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 32,
        "v1": 33
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 34,
        "v1": 35
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 36,
        "v1": 37,
        "curve": 0
    }, {
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 0.1,
        "cMask": ["wall"],
        "v0": 38,
        "v1": 39,
        "curve": 0
    }, {
        "vis": true,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 46,
        "v1": 47,
        "color": "C7E6BD"
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 48,
        "v1": 49
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 50,
        "v1": 51
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 52,
        "v1": 53
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 54,
        "v1": 55
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 56,
        "v1": 57
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 58,
        "v1": 59
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 60,
        "v1": 61
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 62,
        "v1": 63
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 64,
        "v1": 65
    }, {
        "vis": false,
        "bCoef": 2,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 66,
        "v1": 67
    }, {
        "vis": false,
        "v0": 68,
        "v1": 69
    }, {
        "vis": false,
        "v0": 70,
        "v1": 71
    }, {
        "vis": false,
        "v0": 72,
        "v1": 73
    }, {
        "vis": false,
        "v0": 74,
        "v1": 75
    }, {
        "vis": false,
        "v0": 76,
        "v1": 77
    }, {
        "vis": false,
        "v0": 78,
        "v1": 79
    }, {
        "vis": false,
        "v0": 80,
        "v1": 81
    }, {
        "vis": false,
        "v0": 82,
        "v1": 83
    }, {
        "vis": false,
        "v0": 84,
        "v1": 85
    }, {
        "vis": false,
        "v0": 86,
        "v1": 87
    }],
    "goals": [{
        "p0": [-550, 100],
        "p1": [-550, -100],
        "team": "red"
    }, {
        "p0": [550, 100],
        "p1": [550, -100],
        "team": "blue"
    }],
    "discs": [{
        "pos": [-550, 100],
        "trait": "goalPost",
        "color": "FFFFFF",
        "radius": 5.5,
        "bCoef": 1
    }, {
        "pos": [-550, -100],
        "trait": "goalPost",
        "color": "FFFFFF",
        "radius": 5.5,
        "bCoef": 1
    }, {
        "pos": [550, 100],
        "trait": "goalPost",
        "color": "FFFFFF",
        "radius": 5.5,
        "bCoef": 1
    }, {
        "pos": [550, -100],
        "trait": "goalPost",
        "color": "FFFFFF",
        "radius": 5.5,
        "bCoef": 1
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -320,
        "trait": "ballArea"
    }, {
        "normal": [0, -1],
        "dist": -320,
        "trait": "ballArea"
    }, {
        "normal": [0, 1],
        "dist": -350,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -350,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -630,
        "bCoef": 0.1
    }, {
        "normal": [-1, 0],
        "dist": -630,
        "bCoef": 0.1
    }],
    "traits": {
        "ballArea": {
            "vis": false,
            "bCoef": 1,
            "cMask": ["ball"]
        },
        "goalPost": {
            "radius": 8,
            "invMass": 0,
            "bCoef": 0.5
        },
        "goalNet": {
            "vis": true,
            "bCoef": 0.1,
            "cMask": ["ball"]
        },
        "kickOffBarrier": {
            "vis": false,
            "bCoef": 0.1,
            "cGroup": ["redKO", "blueKO"],
            "cMask": ["red", "blue"]
        }
    },
    "playerPhysics": {
        "bCoef": 0.5,
        "invMass": 0.3,
        "damping": 0.96,
        "acceleration": 0.105,
        "kickingAcceleration": 0.073,
        "kickingDamping": 0.97,
        "kickStrength": 5.7
    },
    "ballPhysics": {
        "radius": 6.4,
        "bCoef": 0.5,
        "invMass": 1,
        "damping": 0.99,
        "color": "7cfc00",
        "cMask": ["all"],
        "cGroup": ["ball"]
    }
}`;