export var stadiumText: string = `{
    "name": "G.Buffon So Hot Map&[GB]",
    "width": 920,
    "height": 550,
    "spawnDistance": 350,
    "bg": {
        "type": "grass",
        "width": 800,
        "height": 480,
        "kickOffRadius": 80,
        "cornerRadius": 0
    },
    "vertexes": [{
        "x": -800,
        "y": 480,
        "trait": "ballArea"
    }, {
        "x": -800,
        "y": -480,
        "trait": "ballArea"
    }, {
        "x": 800,
        "y": 480,
        "trait": "ballArea"
    }, {
        "x": 800,
        "y": -480,
        "trait": "ballArea"
    }, {
        "x": 0,
        "y": 550,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": 80,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -80,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -550,
        "trait": "kickOffBarrier"
    }, {
        "bCoef": 1,
        "trait": "ballArea",
        "x": -800,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -800,
        "y": -130
    }, {
        "bCoef": 1,
        "trait": "ballArea",
        "x": 800,
        "y": 130
    }, {
        "bCoef": 1,
        "x": 800,
        "y": -130,
        "trait": "ballArea"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "x": -800,
        "y": 130,
        "curve": 10,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "x": -845,
        "y": 115,
        "curve": -20,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "x": -800,
        "y": -130,
        "curve": -10,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "x": -845,
        "y": -115,
        "curve": -20,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "x": 845,
        "y": 115,
        "curve": 10,
        "trait": "goalNet"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "x": 800,
        "y": 130,
        "curve": 10,
        "trait": "goalNet"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "x": 800,
        "y": -130,
        "trait": "goalNet",
        "curve": 10
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "x": 845,
        "y": -115,
        "trait": "goalNet",
        "curve": 10
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -625,
        "y": -175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -625,
        "y": 175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -450,
        "y": -255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -450,
        "y": 255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -450,
        "y": -100,
        "curve": 150
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -450,
        "y": 100,
        "curve": 150
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 175,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 625,
        "y": 175,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 625,
        "y": -175
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 450,
        "y": -255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 450,
        "y": 255
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 450,
        "y": -100,
        "curve": -150
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 450,
        "y": 100,
        "curve": -150
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -770,
        "y": -480,
        "curve": 90
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -450,
        "curve": 90
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 450,
        "curve": 90
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -770,
        "y": 480,
        "curve": 90
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 450
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 770,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 770,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -450
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -500,
        "y": 10,
        "curve": 100
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -500,
        "y": 15,
        "curve": 100
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 500,
        "y": 10,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 500,
        "y": 15,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -480,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": -130,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 130,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 480,
        "color": "C7E6BD"
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": -800,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["wall"],
        "x": 800,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 802,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 802,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 800,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 800,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -801,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -801,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -802,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -802,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -803,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -803,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -801,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -801,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -802,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -802,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -803,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -803,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 800,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -800,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -800,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 800,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": 127
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 801,
        "y": 477
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 804,
        "y": 129
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -814,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -814,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -807,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -807,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -805,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -805,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -810,
        "y": 133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -810,
        "y": 483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -819,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -819,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -816,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -812,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -812,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -805,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -805,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -816,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -816,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -808,
        "y": -479
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -808,
        "y": -129
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -809,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -809,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -814,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -814,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -815,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -813,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -807,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -807,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -818,
        "y": 480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -810,
        "y": 133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -810,
        "y": 483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -817,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -811,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -819,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -819,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 809,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 809,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 810,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 810,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": -484
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": -134
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 806,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 806,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 812,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 812,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 804,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 804,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": -133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": -480
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": -130
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": -132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": 133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": 483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 809,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 809,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 808,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 810,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 810,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 805,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": 134
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": 484
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 806,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 806,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 812,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 812,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 804,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 804,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": 133
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": 483
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 818,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 817,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 819,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": 131
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 814,
        "y": 481
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": 134
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 822,
        "y": 484
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 815,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 821,
        "y": 482
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": 132
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 813,
        "y": 482
    }],
    "segments": [{
        "v0": 4,
        "v1": 5,
        "trait": "kickOffBarrier"
    }, {
        "v0": 5,
        "v1": 6,
        "trait": "kickOffBarrier",
        "curve": 180,
        "cGroup": ["blueKO"]
    }, {
        "v0": 5,
        "v1": 6,
        "trait": "kickOffBarrier",
        "curve": -180,
        "cGroup": ["redKO"]
    }, {
        "v0": 6,
        "v1": 7,
        "trait": "kickOffBarrier"
    }, {
        "curve": 0,
        "vis": false,
        "bCoef": 1,
        "trait": "ballArea",
        "v0": 0,
        "v1": 8
    }, {
        "curve": 0,
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 1,
        "v1": 9
    }, {
        "curve": 0,
        "vis": false,
        "bCoef": 1,
        "trait": "ballArea",
        "v0": 2,
        "v1": 10
    }, {
        "curve": 0,
        "vis": false,
        "bCoef": 1,
        "v0": 11,
        "v1": 3,
        "trait": "ballArea"
    }, {
        "curve": 10,
        "vis": true,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "v0": 12,
        "v1": 13,
        "color": "C7E6BD"
    }, {
        "curve": -10,
        "vis": true,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "goalNet",
        "v0": 14,
        "v1": 15,
        "color": "C7E6BD"
    }, {
        "curve": -20,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1.5,
        "v0": 15,
        "v1": 13
    }, {
        "curve": 10,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "v0": 16,
        "v1": 17,
        "trait": "goalNet"
    }, {
        "curve": 10,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "v0": 18,
        "v1": 19,
        "trait": "goalNet"
    }, {
        "curve": 20,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "v0": 19,
        "v1": 16
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 20,
        "v1": 21
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 22,
        "v1": 23
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 21,
        "v1": 23
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 24,
        "v1": 25
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 26,
        "v1": 27
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 27,
        "v1": 25
    }, {
        "curve": 150,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 28,
        "v1": 29
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 30,
        "v1": 31
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 32,
        "v1": 33
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 33,
        "v1": 31
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 34,
        "v1": 35
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 36,
        "v1": 37
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 35,
        "v1": 37
    }, {
        "curve": -150,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 38,
        "v1": 39
    }, {
        "curve": 90,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 40,
        "v1": 41
    }, {
        "curve": 90,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 42,
        "v1": 43
    }, {
        "curve": -90,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 44,
        "v1": 45
    }, {
        "curve": -90,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 46,
        "v1": 47
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 48,
        "v1": 49
    }, {
        "curve": 100,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 48,
        "v1": 49
    }, {
        "curve": 100,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 50,
        "v1": 51,
        "x": 500,
        "y": 10
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 50,
        "v1": 51,
        "x": 500,
        "y": 10
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 52,
        "v1": 53
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 54,
        "v1": 55
    }, {
        "curve": 0,
        "vis": true,
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 56,
        "v1": 57,
        "color": "C7E6BD"
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 58,
        "v1": 59
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 60,
        "v1": 61
    }, {
        "curve": 0,
        "vis": true,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["wall"],
        "v0": 62,
        "v1": 63
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 64,
        "v1": 65
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 66,
        "v1": 67
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 68,
        "v1": 69
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 72,
        "v1": 73
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 74,
        "v1": 75
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 76,
        "v1": 77
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 78,
        "v1": 79
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 80,
        "v1": 81
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 82,
        "v1": 83
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 84,
        "v1": 85,
        "y": -481
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 86,
        "v1": 87
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 89,
        "v1": 90
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 93,
        "v1": 94
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 95,
        "v1": 96
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 97,
        "v1": 98
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 99,
        "v1": 100
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 101,
        "v1": 102
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 103,
        "v1": 104
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 105,
        "v1": 106
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 107,
        "v1": 108
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 109,
        "v1": 110
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 111,
        "v1": 112
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 113,
        "v1": 114
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 116,
        "v1": 117
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 118,
        "v1": 119
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 120,
        "v1": 121
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 122,
        "v1": 123
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 124,
        "v1": 125
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 126,
        "v1": 127
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 128,
        "v1": 129
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 130,
        "v1": 131
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 132,
        "v1": 133
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 134,
        "v1": 135
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 137,
        "v1": 138
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 139,
        "v1": 140
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 141,
        "v1": 142
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 143,
        "v1": 144
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 145,
        "v1": 146
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 147,
        "v1": 148
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 149,
        "v1": 150
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 151,
        "v1": 152
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 153,
        "v1": 154
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 155,
        "v1": 156
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 158,
        "v1": 159
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 160,
        "v1": 161
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 162,
        "v1": 163
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 164,
        "v1": 165
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 166,
        "v1": 167
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 168,
        "v1": 169
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 170,
        "v1": 171
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 172,
        "v1": 173
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 174,
        "v1": 175
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 177,
        "v1": 178
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 179,
        "v1": 180
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 181,
        "v1": 182
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 183,
        "v1": 184
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 185,
        "v1": 186
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 187,
        "v1": 188
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 189,
        "v1": 190
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 191,
        "v1": 192
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 193,
        "v1": 194
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 196,
        "v1": 197
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 198,
        "v1": 199
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 200,
        "v1": 201
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 202,
        "v1": 203
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 204,
        "v1": 205
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 206,
        "v1": 207
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 208,
        "v1": 209
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 210,
        "v1": 211
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 212,
        "v1": 213
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 215,
        "v1": 216
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 217,
        "v1": 218
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 219,
        "v1": 220
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 221,
        "v1": 222
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 223,
        "v1": 224
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 225,
        "v1": 226
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 227,
        "v1": 228
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 229,
        "v1": 230
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 231,
        "v1": 232
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 234,
        "v1": 235
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 236,
        "v1": 237
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 238,
        "v1": 239
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 240,
        "v1": 241
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 242,
        "v1": 243
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 244,
        "v1": 245
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 246,
        "v1": 247
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 248,
        "v1": 249
    }, {
        "vis": false,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "v0": 250,
        "v1": 251
    }],
    "goals": [{
        "team": "red",
        "p0": [-800, -130],
        "p1": [-800, 130]
    }, {
        "team": "blue",
        "p0": [800, -130],
        "p1": [800, 130]
    }],
    "discs": [{
        "radius": 5.5,
        "invMass": 0,
        "pos": [-800, 130],
        "bCoef": 1,
        "trait": "goalPost"
    }, {
        "radius": 5.5,
        "invMass": 0,
        "pos": [-800, -130],
        "bCoef": 1,
        "trait": "goalPost"
    }, {
        "radius": 5.5,
        "invMass": 0,
        "pos": [800, -130],
        "bCoef": 1,
        "trait": "goalPost",
        "_selected": true
    }, {
        "radius": 5.5,
        "invMass": 0,
        "pos": [800, 130],
        "bCoef": 1,
        "trait": "goalPost"
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -480,
        "trait": "ballArea"
    }, {
        "normal": [0, -1],
        "dist": -480,
        "trait": "ballArea"
    }, {
        "normal": [0, 1],
        "dist": -550,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -550,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -920,
        "bCoef": 0.1
    }, {
        "dist": -920,
        "normal": [-1, 0]
    }],
    "traits": {
        "ballArea": {
            "vis": false,
            "bCoef": 1,
            "cMask": ["ball"]
        },
        "goalPost": {
            "radius": 8,
            "invMass": 0,
            "bCoef": 0.5
        },
        "goalNet": {
            "vis": true,
            "bCoef": 0.1,
            "cMask": ["ball"]
        },
        "kickOffBarrier": {
            "vis": false,
            "bCoef": 0.1,
            "cGroup": ["redKO", "blueKO"],
            "cMask": ["red", "blue"]
        }
    },
    "playerPhysics": {
        "bCoef": 0.5,
        "invMass": 0.3,
        "damping": 0.96,
        "acceleration": 0.1,
        "kickingAcceleration": 0.07,
        "kickingDamping": 0.97,
        "kickStrength": 5.7
    },
    "ballPhysics": {
        "radius": 6.4,
        "bCoef": 0.5,
        "invMass": 1,
        "damping": 0.99,
        "color": "7cfc00",
        "cMask": ["all"],
        "cGroup": ["ball"]
    }
}`;