export var stadiumText: string = `{
    "name": "Haxbotron 4vs4",
    "width": 840,
    "height": 380,
    "bg": {
        "type": "grass",
        "width": 740,
        "height": 340,
        "kickOffRadius": 80
    },
    "vertexes": [{
        "x": -740,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 0,
        "y": 380,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": 80,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": -80,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": -380,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": -740,
        "y": -340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 110,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 110,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -110,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -340,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -110,
        "bCoef": 0.1,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -785,
        "y": -90,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -785,
        "y": 90,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 785,
        "y": -90,
        "cMask": ["ball"]
    }, {
        "x": 785,
        "y": 90,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -742,
        "y": -340,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": -741,
        "y": -112,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": -743,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -743,
        "y": -112,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -115,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": -742,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -743,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -743,
        "y": -112,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -115,
        "cMask": ["ball"]
    }, {
        "x": -744,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": -742,
        "y": 113,
        "cMask": ["ball"]
    }, {
        "x": -742,
        "y": 113,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -115,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": 743,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": 743,
        "y": -116,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": 743,
        "y": -341,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": 743,
        "y": -113,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": 742,
        "y": 109,
        "cMask": ["ball"]
    }, {
        "x": 742,
        "y": 334,
        "cMask": ["ball"]
    }, {
        "x": 742,
        "y": 109,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": 742,
        "y": 337,
        "bCoef": 0.1,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -342,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -117,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -342,
        "cMask": ["ball"]
    }, {
        "x": 744,
        "y": -114,
        "cMask": ["ball"]
    }, {
        "x": 751,
        "y": -343,
        "cMask": ["ball"]
    }, {
        "x": 752,
        "y": -117,
        "cMask": ["ball"]
    }, {
        "x": 757,
        "y": -345,
        "cMask": ["ball"]
    }, {
        "x": 760,
        "y": -115,
        "cMask": ["ball"]
    }, {
        "x": 764,
        "y": -346,
        "cMask": ["ball"]
    }, {
        "x": 767,
        "y": -113,
        "cMask": ["ball"]
    }, {
        "x": 748,
        "y": 338,
        "cMask": ["ball"]
    }, {
        "x": 749,
        "y": 112,
        "cMask": ["ball"]
    }, {
        "x": 755,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 755,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 764,
        "y": 107,
        "cMask": ["ball"]
    }, {
        "x": 765,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -746,
        "y": 334,
        "cMask": ["ball"]
    }, {
        "x": -752,
        "y": 111,
        "cMask": ["ball"]
    }, {
        "x": -756,
        "y": 332,
        "cMask": ["ball"]
    }, {
        "x": -762,
        "y": 108,
        "cMask": ["ball"]
    }, {
        "x": -764,
        "y": 331,
        "cMask": ["ball"]
    }, {
        "x": -769,
        "y": 109,
        "cMask": ["ball"]
    }, {
        "x": -774,
        "y": 328,
        "cMask": ["ball"]
    }, {
        "x": -758,
        "y": 113,
        "cMask": ["ball"]
    }, {
        "x": -747,
        "y": 117,
        "cMask": ["ball"]
    }, {
        "x": -752,
        "y": 328,
        "cMask": ["ball"]
    }, {
        "x": -751,
        "y": -341,
        "cMask": ["ball"]
    }, {
        "x": -752,
        "y": -113,
        "cMask": ["ball"]
    }, {
        "x": -769,
        "y": -344,
        "cMask": ["ball"]
    }, {
        "x": -771,
        "y": -115,
        "cMask": ["ball"]
    }, {
        "x": -763,
        "y": -346,
        "cMask": ["ball"]
    }, {
        "x": -765,
        "y": -111,
        "cMask": ["ball"]
    }, {
        "x": -758,
        "y": -347,
        "cMask": ["ball"]
    }, {
        "x": -759,
        "y": -121,
        "cMask": ["ball"]
    }, {
        "x": -777,
        "y": -347,
        "cMask": ["ball"]
    }, {
        "x": -776,
        "y": -113,
        "cMask": ["ball"]
    }, {
        "x": -748,
        "y": -120,
        "cMask": ["ball"]
    }],
    "segments": [{
        "v0": 0,
        "v1": 1,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 2,
        "v1": 3,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 4,
        "v1": 5,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 6,
        "v1": 7,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 8,
        "v1": 9,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "v0": 9,
        "v1": 10,
        "bCoef": 0.1,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["blueKO"]
    }, {
        "v0": 10,
        "v1": 9,
        "bCoef": 0.1,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO"]
    }, {
        "v0": 10,
        "v1": 11,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "v0": 12,
        "v1": 13,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 14,
        "v1": 15,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 16,
        "v1": 17,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 18,
        "v1": 19,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 20,
        "v1": 21,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 22,
        "v1": 23,
        "bCoef": 0.1,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 25,
        "v1": 24,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 26,
        "v1": 27,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 28,
        "v1": 29,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 30,
        "v1": 31,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 33,
        "v1": 32,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 34,
        "v1": 35,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 36,
        "v1": 37,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 38,
        "v1": 39,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 40,
        "v1": 41,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 42,
        "v1": 43,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 44,
        "v1": 45,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 48,
        "v1": 49,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 50,
        "v1": 51,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 55,
        "v1": 56,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 58,
        "v1": 59,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 61,
        "v1": 62,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 63,
        "v1": 64,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 65,
        "v1": 66,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 37,
        "v1": 38,
        "curve": 20,
        "curveF": 5.671281819617709,
        "color": "C7E6BD"
    }, {
        "v0": 35,
        "v1": 33,
        "curve": 20,
        "curveF": 5.671281819617709,
        "color": "C7E6BD"
    }, {
        "v0": 67,
        "v1": 68,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 69,
        "v1": 70,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 69,
        "v1": 70,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 69,
        "v1": 70,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 71,
        "v1": 72,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 73,
        "v1": 74,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 75,
        "v1": 76,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 65,
        "v1": 66,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 65,
        "v1": 77,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 65,
        "v1": 77,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 78,
        "v1": 77,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 79,
        "v1": 80,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 81,
        "v1": 82,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 81,
        "v1": 82,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 54,
        "v1": 83,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 84,
        "v1": 85,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 86,
        "v1": 87,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 88,
        "v1": 89,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 84,
        "v1": 85,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 90,
        "v1": 87,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 91,
        "v1": 92,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 93,
        "v1": 94,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 95,
        "v1": 96,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 97,
        "v1": 98,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 99,
        "v1": 100,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 101,
        "v1": 102,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 50,
        "v1": 103,
        "vis": false,
        "cMask": ["ball"]
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -340,
        "cMask": ["ball"]
    }, {
        "normal": [0, -1],
        "dist": -340,
        "cMask": ["ball"]
    }, {
        "normal": [0, 1],
        "dist": -380,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -380,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -840,
        "bCoef": 0.1
    }, {
        "normal": [-1, 0],
        "dist": -840,
        "bCoef": 0.1
    }],
    "goals": [{
        "p0": [-740, 110],
        "p1": [-740, -110],
        "team": "red"
    }, {
        "p0": [740, -110],
        "p1": [740, 110],
        "team": "blue"
    }],
    "discs": [{
        "pos": [740, -110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [740, 110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [-740, 110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [-740, -110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }],
    "playerPhysics": {
        "invMass": 0.3,
        "acceleration": 0.105,
        "kickingAcceleration": 0.073,
        "kickingDamping": 0.97,
        "kickStrength": 5.7
    },
    "ballPhysics": {
        "radius": 6.4,
        "color": "7CFC00"
    },
    "spawnDistance": 350
}`