export var stadiumText: string = `{
    "name": "G.Buffon Hot Classic&[GB]",
    "width": 420,
    "height": 200,
    "spawnDistance": 170,
    "bg": {
        "type": "grass",
        "width": 370,
        "height": 170,
        "kickOffRadius": 75,
        "cornerRadius": 0
    },
    "vertexes": [{
        "x": -370,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": -370,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": -370,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": -370,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 370,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": 370,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": 370,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": 370,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 0,
        "y": 200,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": 75,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -75,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": -200,
        "trait": "kickOffBarrier"
    }, {
        "x": -370,
        "y": -64,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": -400,
        "y": -44,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": -400,
        "y": 44,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": -370,
        "y": 64,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": 370,
        "y": -64,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": 400,
        "y": -44,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": 400,
        "y": 44,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "x": 370,
        "y": 64,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -371,
        "y": -171
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -371,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": -72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": -170,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": -70,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -376,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -376,
        "y": -68
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -380,
        "y": -174
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -383,
        "y": -69
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -379,
        "y": -74
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -384,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -393,
        "y": -173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": -72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": -170,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": -70,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -376,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -376,
        "y": -68
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -380,
        "y": -174
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -383,
        "y": -69
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -379,
        "y": -74
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -384,
        "y": -170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -393,
        "y": -173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -371,
        "y": 72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -371,
        "y": 170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": 72,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -373,
        "y": 172,
        "curve": 0
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": 72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -372,
        "y": 172
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": 72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -374,
        "y": 172
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": 72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -375,
        "y": 174
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -379,
        "y": 68
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -382,
        "y": 173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -378,
        "y": 168
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -383,
        "y": 72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -392,
        "y": 69
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -392,
        "y": 169
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -386,
        "y": 166
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": -399,
        "y": 173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 371,
        "y": 67
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 371,
        "y": 170
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 376,
        "y": 68
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 377,
        "y": 173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 380,
        "y": 168
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 383,
        "y": 67
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 386,
        "y": 169
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 387,
        "y": 62
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 387,
        "y": 164
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 392,
        "y": 169
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 395,
        "y": 62
    }, {
        "x": 371,
        "y": -70,
        "trait": "ballArea"
    }, {
        "x": 371,
        "y": -176,
        "trait": "ballArea"
    }, {
        "x": 371,
        "y": -176,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 372,
        "y": -173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 372,
        "y": -70
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 377,
        "y": -172
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 378,
        "y": -67
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 381,
        "y": -72
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 384,
        "y": -173
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 387,
        "y": -71
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 388,
        "y": -178
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 388,
        "y": -76
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 393,
        "y": -71
    }, {
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "x": 396,
        "y": -178
    }, {
        "x": 380,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": 380,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 390,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": 390,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 400,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": 400,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 410,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": 410,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": 380,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": 380,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": 390,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": 390,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": 400,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": 400,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": 410,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": 410,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": -380,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": -380,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": -390,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": -390,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": -400,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": -400,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": -410,
        "y": -64,
        "trait": "ballArea"
    }, {
        "x": -410,
        "y": -170,
        "trait": "ballArea"
    }, {
        "x": -380,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": -380,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": -390,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": -390,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": -400,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": -400,
        "y": 64,
        "trait": "ballArea"
    }, {
        "x": -410,
        "y": 170,
        "trait": "ballArea"
    }, {
        "x": -410,
        "y": 64,
        "trait": "ballArea"
    }],
    "segments": [{
        "v0": 0,
        "v1": 1,
        "trait": "ballArea"
    }, {
        "v0": 2,
        "v1": 3,
        "trait": "ballArea"
    }, {
        "v0": 4,
        "v1": 5,
        "trait": "ballArea"
    }, {
        "v0": 6,
        "v1": 7,
        "trait": "ballArea"
    }, {
        "v0": 12,
        "v1": 13,
        "trait": "goalNet",
        "curve": -90,
        "color": "ffffff"
    }, {
        "v0": 13,
        "v1": 14,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "v0": 14,
        "v1": 15,
        "trait": "goalNet",
        "curve": -90,
        "color": "ffffff"
    }, {
        "v0": 16,
        "v1": 17,
        "trait": "goalNet",
        "curve": 90,
        "color": "ffffff"
    }, {
        "v0": 17,
        "v1": 18,
        "trait": "goalNet",
        "color": "ffffff"
    }, {
        "v0": 18,
        "v1": 19,
        "trait": "goalNet",
        "curve": 90,
        "color": "ffffff"
    }, {
        "v0": 8,
        "v1": 9,
        "trait": "kickOffBarrier"
    }, {
        "v0": 9,
        "v1": 10,
        "trait": "kickOffBarrier",
        "curve": 180,
        "cGroup": ["blueKO"]
    }, {
        "v0": 9,
        "v1": 10,
        "trait": "kickOffBarrier",
        "curve": -180,
        "cGroup": ["redKO"]
    }, {
        "v0": 10,
        "v1": 11,
        "trait": "kickOffBarrier"
    }, {
        "v0": 95,
        "v1": 96,
        "trait": "ballArea",
        "x": 380
    }, {
        "v0": 97,
        "v1": 98,
        "trait": "ballArea",
        "x": 390
    }, {
        "v0": 99,
        "v1": 100,
        "trait": "ballArea",
        "x": 400
    }, {
        "v0": 101,
        "v1": 102,
        "trait": "ballArea",
        "x": 410
    }, {
        "v0": 103,
        "v1": 104,
        "trait": "ballArea",
        "x": 380
    }, {
        "v0": 105,
        "v1": 106,
        "trait": "ballArea",
        "x": 390
    }, {
        "v0": 107,
        "v1": 108,
        "trait": "ballArea",
        "x": 400
    }, {
        "v0": 109,
        "v1": 110,
        "trait": "ballArea",
        "x": 410
    }, {
        "v0": 111,
        "v1": 112,
        "trait": "ballArea",
        "x": -380
    }, {
        "v0": 113,
        "v1": 114,
        "trait": "ballArea",
        "x": -390
    }, {
        "v0": 115,
        "v1": 116,
        "trait": "ballArea",
        "x": -400
    }, {
        "v0": 117,
        "v1": 118,
        "trait": "ballArea",
        "x": -410
    }, {
        "v0": 119,
        "v1": 120,
        "trait": "ballArea",
        "x": -380
    }, {
        "v0": 121,
        "v1": 122,
        "trait": "ballArea",
        "x": -390
    }, {
        "v0": 123,
        "v1": 124,
        "trait": "ballArea",
        "x": -400
    }, {
        "v0": 125,
        "v1": 126,
        "trait": "ballArea",
        "x": -410
    }],
    "goals": [{
        "p0": [-370, 64],
        "p1": [-370, -64],
        "team": "red"
    }, {
        "p0": [370, 64],
        "p1": [370, -64],
        "team": "blue"
    }],
    "discs": [{
        "pos": [-370, 64],
        "trait": "goalPost",
        "color": "ffffff",
        "radius": 5.5
    }, {
        "pos": [-370, -64],
        "trait": "goalPost",
        "color": "ffffff",
        "radius": 5.5
    }, {
        "pos": [370, 64],
        "trait": "goalPost",
        "color": "ffffff",
        "radius": 5.5
    }, {
        "pos": [370, -64],
        "trait": "goalPost",
        "color": "ffffff",
        "radius": 5.5
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -170,
        "trait": "ballArea"
    }, {
        "normal": [0, -1],
        "dist": -170,
        "trait": "ballArea"
    }, {
        "normal": [0, 1],
        "dist": -200,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -200,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -420,
        "bCoef": 0.1
    }, {
        "normal": [-1, 0],
        "dist": -420,
        "bCoef": 0.1
    }],
    "traits": {
        "ballArea": {
            "vis": false,
            "bCoef": 1,
            "cMask": ["ball"]
        },
        "goalPost": {
            "radius": 8,
            "invMass": 0,
            "bCoef": 0.5
        },
        "goalNet": {
            "vis": true,
            "bCoef": 0.1,
            "cMask": ["ball"]
        },
        "kickOffBarrier": {
            "vis": false,
            "bCoef": 0.1,
            "cGroup": ["redKO", "blueKO"],
            "cMask": ["red", "blue"]
        }
    },
    "playerPhysics": {
        "bCoef": 0.5,
        "invMass": 0.3,
        "damping": 0.96,
        "acceleration": 0.105,
        "kickingAcceleration": 0.073,
        "kickingDamping": 0.97,
        "kickStrength": 5.7
    },
    "ballPhysics": {
        "radius": 6.4,
        "bCoef": 0.5,
        "invMass": 1,
        "damping": 0.99,
        "color": "7cfc00",
        "cGroup": ["ball"],
        "cMask": ["all"]
    }
}`;