export var stadiumText: string = `{
    "name": "G.Buffon Hot Huge&[GB]",
    "width": 840,
    "height": 380,
    "bg": {
        "type": "grass",
        "width": 740,
        "height": 340,
        "kickOffRadius": 80
    },
    "vertexes": [{
        "x": -740,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 0,
        "y": 380,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": 80,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": -80,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": 0,
        "y": -380,
        "bCoef": 0.1,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "x": -740,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 110,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 110,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -110,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": 740,
        "y": -110,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -340,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": -80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 80,
        "cMask": ["wall"]
    }, {
        "x": 0,
        "y": 340,
        "cMask": ["wall"]
    }, {
        "x": -740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -785,
        "y": -90,
        "cMask": ["ball"]
    }, {
        "x": -740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -785,
        "y": 90,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 785,
        "y": -90,
        "cMask": ["ball"]
    }, {
        "x": 785,
        "y": 90,
        "cMask": ["ball"]
    }, {
        "x": 740,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -741,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -748,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -748,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -748,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -748,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -756,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -756,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -756,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -756,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -762,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -762,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -762,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -762,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -770,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -770,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -770,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -770,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 748,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 748,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 748,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 748,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 756,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 756,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 756,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 756,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 762,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 762,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 762,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 762,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 770,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 770,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 770,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 770,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -747,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -747,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -747,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -747,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": -746,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": -746,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": -746,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": -746,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 747,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 747,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 747,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 747,
        "y": -340,
        "cMask": ["ball"]
    }, {
        "x": 746,
        "y": 340,
        "cMask": ["ball"]
    }, {
        "x": 746,
        "y": 110,
        "cMask": ["ball"]
    }, {
        "x": 746,
        "y": -110,
        "cMask": ["ball"]
    }, {
        "x": 746,
        "y": -340,
        "cMask": ["ball"]
    }],
    "segments": [{
        "v0": 0,
        "v1": 1,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 2,
        "v1": 3,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 4,
        "v1": 5,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 6,
        "v1": 7,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 8,
        "v1": 9,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "v0": 9,
        "v1": 10,
        "bCoef": 0.1,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["blueKO"]
    }, {
        "v0": 10,
        "v1": 9,
        "bCoef": 0.1,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO"]
    }, {
        "v0": 10,
        "v1": 11,
        "bCoef": 0.1,
        "vis": false,
        "cMask": ["red", "blue"],
        "cGroup": ["redKO", "blueKO"]
    }, {
        "v0": 12,
        "v1": 13,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 14,
        "v1": 15,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 16,
        "v1": 17,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 18,
        "v1": 19,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 20,
        "v1": 21,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 22,
        "v1": 23,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 25,
        "v1": 24,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 26,
        "v1": 27,
        "curve": 180,
        "curveF": 6.123233995736766e-17,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 28,
        "v1": 29,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 30,
        "v1": 31,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "v0": 33,
        "v1": 32,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 34,
        "v1": 35,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 36,
        "v1": 37,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 38,
        "v1": 39,
        "curve": 20,
        "curveF": 5.671281819617709,
        "cMask": ["ball"],
        "color": "C7E6BD"
    }, {
        "v0": 37,
        "v1": 38,
        "curve": 20,
        "curveF": 5.671281819617709,
        "color": "C7E6BD"
    }, {
        "v0": 35,
        "v1": 33,
        "curve": 20,
        "curveF": 5.671281819617709,
        "color": "C7E6BD"
    }, {
        "v0": 41,
        "v1": 42,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 43,
        "v1": 44,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 45,
        "v1": 46,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 47,
        "v1": 48,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 49,
        "v1": 50,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 51,
        "v1": 52,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 53,
        "v1": 54,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 55,
        "v1": 56,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 57,
        "v1": 58,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 59,
        "v1": 60,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 61,
        "v1": 62,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 63,
        "v1": 64,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 65,
        "v1": 66,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 67,
        "v1": 68,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 69,
        "v1": 70,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 71,
        "v1": 72,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 73,
        "v1": 74,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 75,
        "v1": 76,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 77,
        "v1": 78,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 79,
        "v1": 80,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 81,
        "v1": 82,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 83,
        "v1": 84,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 85,
        "v1": 86,
        "vis": false,
        "cMask": ["ball"]
    }, {
        "v0": 87,
        "v1": 88,
        "vis": false,
        "cMask": ["ball"]
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -340,
        "cMask": ["ball"]
    }, {
        "normal": [0, -1],
        "dist": -340,
        "cMask": ["ball"]
    }, {
        "normal": [0, 1],
        "dist": -380,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -380,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -840,
        "bCoef": 0.1
    }, {
        "normal": [-1, 0],
        "dist": -840,
        "bCoef": 0.1
    }],
    "goals": [{
        "p0": [-740, 110],
        "p1": [-740, -110],
        "team": "red"
    }, {
        "p0": [740, -110],
        "p1": [740, 110],
        "team": "blue"
    }],
    "discs": [{
        "radius": 6.4,
        "color": "7CFC00",
        "cGroup": ["ball", "kick", "score"]
    }, {
        "pos": [740, -110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [740, 110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [-740, 110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }, {
        "pos": [-740, -110],
        "radius": 5.5,
        "bCoef": 1,
        "invMass": 0
    }],
    "playerPhysics": {
        "invMass": 0.3,
        "acceleration": 0.105,
        "kickingAcceleration": 0.073,
        "kickingDamping": 0.97,
        "kickStrength": 5.7
    },
    "ballPhysics": "disc0",
    "spawnDistance": 350
}`;