export var stadiumText: string = `{
    "name": "G.Buffon Hot Small&[GB]",
    "width": 420,
    "height": 200,
    "spawnDistance": 130,
    "bg": {
        "type": "grass",
        "width": 320,
        "height": 130,
        "kickOffRadius": 70,
        "cornerRadius": 0
    },
    "vertexes": [{
        "x": -320,
        "y": 130,
        "cMask": ["wall"],
        "trait": "ballArea",
        "color": "C7E6BD",
        "curve": 0
    }, {
        "x": -320,
        "y": 55,
        "trait": "ballArea"
    }, {
        "x": -320,
        "y": -55,
        "trait": "ballArea"
    }, {
        "x": -320,
        "y": -130,
        "cMask": ["wall"],
        "trait": "ballArea",
        "color": "C7E6BD"
    }, {
        "x": 320,
        "y": 130,
        "cMask": ["wall"],
        "trait": "ballArea",
        "color": "C7E6BD",
        "curve": 0
    }, {
        "x": 320,
        "y": 55,
        "trait": "ballArea"
    }, {
        "x": 320,
        "y": -55,
        "trait": "ballArea"
    }, {
        "x": 320,
        "y": -130,
        "cMask": ["wall"],
        "trait": "ballArea",
        "color": "C7E6BD"
    }, {
        "x": 0,
        "y": 200,
        "trait": "kickOffBarrier"
    }, {
        "x": 0,
        "y": 70,
        "cMask": ["wall"],
        "trait": "kickOffBarrier",
        "curve": -180,
        "color": "C7E6BD"
    }, {
        "x": 0,
        "y": -70,
        "cMask": ["wall"],
        "trait": "kickOffBarrier",
        "curve": -180,
        "color": "C7E6BD"
    }, {
        "x": 0,
        "y": -200,
        "trait": "kickOffBarrier"
    }, {
        "x": -320,
        "y": -55,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": -10
    }, {
        "x": -355,
        "y": -40,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": -20
    }, {
        "x": -355,
        "y": 40,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": -20
    }, {
        "x": -320,
        "y": 55,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": -10
    }, {
        "x": 320,
        "y": -55,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": 10
    }, {
        "x": 355,
        "y": -40,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": 20
    }, {
        "x": 355,
        "y": 40,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": 20
    }, {
        "x": 320,
        "y": 55,
        "trait": "goalNet",
        "color": "C7E6BD",
        "curve": 10
    }, {
        "x": 320,
        "y": -55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": -320,
        "y": 55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": 320,
        "y": 55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": -320,
        "y": -55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": 0,
        "y": -130,
        "cMask": ["wall"],
        "curve": 0,
        "color": "C7E6BD"
    }, {
        "x": 0,
        "y": 130,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": -320,
        "y": -55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": -320,
        "y": 55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": 320,
        "y": -55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": 320,
        "y": 55,
        "cMask": ["wall"],
        "color": "C7E6BD"
    }, {
        "x": 322,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": 322,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": 324,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 324,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 326,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 326,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 328,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 328,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": 60,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": 130,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": 59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": 129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 334,
        "y": 59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 334,
        "y": 129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 336,
        "y": 59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 336,
        "y": 129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 338,
        "y": 59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 338,
        "y": 129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 340,
        "y": 59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 340,
        "y": 129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 320,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": 320,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": 322,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 322,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 324,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 324,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 326,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 326,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 328,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 328,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 330,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 332,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 334,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 334,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 336,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 336,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 338,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": 338,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -340,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": -340,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": -338,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -338,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -336,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -336,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -334,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -334,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -332,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -332,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": 58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": 128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": 57,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": 127,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -328,
        "y": 57,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -328,
        "y": 127,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -326,
        "y": 57,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -326,
        "y": 127,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -324,
        "y": 57,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -324,
        "y": 127,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -322,
        "y": 57,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -322,
        "y": 127,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -340,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": -340,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea",
        "curve": 0
    }, {
        "x": -338,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -338,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -336,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -336,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -334,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -334,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -332,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -332,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": -128,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": -58,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -330,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -328,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -328,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -326,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -326,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -324,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -324,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -322,
        "y": -129,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "x": -322,
        "y": -59,
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }],
    "segments": [{
        "v0": 0,
        "v1": 1,
        "trait": "ballArea"
    }, {
        "v0": 2,
        "v1": 3,
        "trait": "ballArea"
    }, {
        "v0": 4,
        "v1": 5,
        "trait": "ballArea"
    }, {
        "v0": 6,
        "v1": 7,
        "trait": "ballArea"
    }, {
        "v0": 12,
        "v1": 13,
        "curve": -10,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 13,
        "v1": 14,
        "curve": -20,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 14,
        "v1": 15,
        "curve": -10,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 16,
        "v1": 17,
        "curve": 10,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 17,
        "v1": 18,
        "curve": 20,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 18,
        "v1": 19,
        "curve": 10,
        "color": "C7E6BD",
        "trait": "goalNet"
    }, {
        "v0": 8,
        "v1": 9,
        "trait": "kickOffBarrier"
    }, {
        "v0": 9,
        "v1": 10,
        "curve": 180,
        "cGroup": ["blueKO"],
        "trait": "kickOffBarrier"
    }, {
        "v0": 9,
        "v1": 10,
        "curve": -180,
        "cGroup": ["redKO"],
        "trait": "kickOffBarrier"
    }, {
        "v0": 10,
        "v1": 11,
        "trait": "kickOffBarrier"
    }, {
        "v0": 3,
        "v1": 7,
        "color": "C7E6BD",
        "bCoef": 0.5,
        "cMask": ["wall"]
    }, {
        "v0": 7,
        "v1": 20,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 4,
        "v1": 0,
        "curve": 0,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 0,
        "v1": 21,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 4,
        "v1": 22,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 3,
        "v1": 23,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 10,
        "v1": 24,
        "curve": 0,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 10,
        "v1": 9,
        "curve": 180,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 10,
        "v1": 9,
        "curve": -180,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 9,
        "v1": 25,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 26,
        "v1": 27,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 28,
        "v1": 29,
        "color": "C7E6BD",
        "cMask": ["wall"]
    }, {
        "v0": 30,
        "v1": 31,
        "curve": 0,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 32,
        "v1": 33,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 34,
        "v1": 35,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 36,
        "v1": 37,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 38,
        "v1": 39,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 40,
        "v1": 41,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 42,
        "v1": 43,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 44,
        "v1": 45,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 46,
        "v1": 47,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 48,
        "v1": 49,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 50,
        "v1": 51,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 52,
        "v1": 53,
        "curve": 0,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 54,
        "v1": 55,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 56,
        "v1": 57,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 58,
        "v1": 59,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 60,
        "v1": 61,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 62,
        "v1": 63,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 64,
        "v1": 65,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 66,
        "v1": 67,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 68,
        "v1": 69,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 70,
        "v1": 71,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 72,
        "v1": 73,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 74,
        "v1": 75,
        "curve": 0,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 76,
        "v1": 77,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 78,
        "v1": 79,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 80,
        "v1": 81,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 82,
        "v1": 83,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 84,
        "v1": 85,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 86,
        "v1": 87,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 88,
        "v1": 89,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 90,
        "v1": 91,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 92,
        "v1": 93,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 94,
        "v1": 95,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 96,
        "v1": 97,
        "curve": 0,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 98,
        "v1": 99,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 100,
        "v1": 101,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 102,
        "v1": 103,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 104,
        "v1": 105,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 106,
        "v1": 107,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 108,
        "v1": 109,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 110,
        "v1": 111,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 112,
        "v1": 113,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 114,
        "v1": 115,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }, {
        "v0": 116,
        "v1": 117,
        "vis": false,
        "color": "C7E6BD",
        "bCoef": 1,
        "cMask": ["ball"],
        "trait": "ballArea"
    }],
    "goals": [{
        "p0": [-320, -55],
        "p1": [-320, 55],
        "team": "red"
    }, {
        "p0": [320, 55],
        "p1": [320, -55],
        "team": "blue"
    }],
    "discs": [{
        "radius": 5.5,
        "pos": [-320, 55],
        "color": "FFFFFF",
        "bCoef": 1,
        "trait": "goalPost"
    }, {
        "radius": 5.5,
        "pos": [-320, -55],
        "color": "FFFFFF",
        "bCoef": 1,
        "trait": "goalPost"
    }, {
        "radius": 5.5,
        "pos": [320, 55],
        "color": "FFFFFF",
        "bCoef": 1,
        "trait": "goalPost"
    }, {
        "radius": 5.5,
        "pos": [320, -55],
        "color": "FFFFFF",
        "bCoef": 1,
        "trait": "goalPost"
    }],
    "planes": [{
        "normal": [0, 1],
        "dist": -130,
        "trait": "ballArea"
    }, {
        "normal": [0, -1],
        "dist": -130,
        "trait": "ballArea"
    }, {
        "normal": [0, 1],
        "dist": -200,
        "bCoef": 0.1
    }, {
        "normal": [0, -1],
        "dist": -200,
        "bCoef": 0.1
    }, {
        "normal": [1, 0],
        "dist": -420,
        "bCoef": 0.1
    }, {
        "normal": [-1, 0],
        "dist": -420,
        "bCoef": 0.1
    }],
    "traits": {
        "ballArea": {
            "vis": false,
            "bCoef": 1,
            "cMask": ["ball"]
        },
        "goalPost": {
            "radius": 8,
            "invMass": 0,
            "bCoef": 0.5
        },
        "goalNet": {
            "vis": true,
            "bCoef": 0.1,
            "cMask": ["ball"]
        },
        "kickOffBarrier": {
            "vis": false,
            "bCoef": 0.1,
            "cGroup": ["redKO", "blueKO"],
            "cMask": ["red", "blue"]
        }
    },
    "ballPhysics": {
        "radius": 6.4,
        "bCoef": 0.5,
        "damping": 0.99,
        "color": "7cfc00",
        "invMass": 1,
        "cMask": ["all"],
        "cGroup": ["ball"]
    },
    "playerPhysics": {
        "kickStrength": 5.7,
        "kickingDamping": 0.97,
        "kickingAcceleration": 0.073,
        "acceleration": 0.105,
        "damping": 0.96,
        "invMass": 0.3,
        "bCoef": 0.5
    }
}`;